# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78a245a8065c8cd47b25b27f8cdc644c"
application_url = "https://doctors-woman-dressed-hitachi.trycloudflare.com"
embedded = true
name = "Mo App Ala"
handle = "mo-app-ala"

[webhooks]
api_version = "2024-01"

[auth]
redirect_urls = [
  "https://doctors-woman-dressed-hitachi.trycloudflare.com/auth/callback",
  "https://doctors-woman-dressed-hitachi.trycloudflare.com/auth/shopify/callback",
  "https://doctors-woman-dressed-hitachi.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "al-amin-extensibility-store.myshopify.com"
automatically_update_urls_on_dev = true
